var phrases = [
	// Shakespeare Quotes
	["All that glitters is not gold",
	"All the world's a stage",
	"Band of brothers",
	"Beast with two backs",
	"Between you and I",
	"Brave new world",
	"By the pricking of my thumbs",
	"The dogs of war",
	"Et tu, Brute?",
	"Even a worm will turn",
	"Friends, Romans, countrymen, lend me your ears",
	"Hoist with his own petard",
	"Honorificabilitudinitatibus",
	"Ides of March",
	"The lady doth protest too much, methinks",
	"Let's kill all the lawyers",
	"Mortal coil",
	"Much Ado About Nothing",
	"Once more unto the breach",
	"The Quality of Mercy",
	"The quality of mercy",
	"A rose by any other name would smell as sweet",
	"Salad days",
	"Star-crossed",
	"There's the rub",
	"Thy name is",
	"To be, or not to be",
	"Tomorrow and tomorrow and tomorrow",
	"What a piece of work is a man",
	"What's past is prologue",
	"Winter of Discontent"],
	// Movie and TV Quotes
	["ALL GLORY TO THE HYPNOTOAD",
	"All work and no play makes Jack a dull boy",
	"Asa Nisi Masa",
	"Charlie Don't Surf",
	"Come with me if you want to live",
	"D'oh!",
	"Did I do that?",
	"Do you feel lucky, punk?",
	"Don't call me Shirley",
	"Don't mention the war",
	"Enna kodumai Saravanan idhu?",
	"The Force",
	"Frankly, my dear, I don't give a damn",
	"Go ahead, make my day",
	"Greed is good",
	"Hasta la vista, baby",
	"I love the smell of napalm in the morning",
	"I, for one, welcome our new insect overlords",
	"I'll be back",
	"I'll be in my bunk",
	"It's never lupus",
	"Klaatu barada nikto",
	"Love means never having to say you're sorry",
	"More cowbell",
	"Not that there's anything wrong with that",
	"Play it again, Sam",
	"Respect my authoritah",
	"Said the actress to the bishop",
	"Save the cheerleader",
	"Save the cheerleader, save the world",
	"Say hello to my little friend!",
	"Shaken, not stirred",
	"So say we all",
	"Stay thirsty, my friends",
	"Stinking badges",
	"Up to eleven",
	"Walk this way",
	"We'll Always Have Paris",
	"What is the matrix",
	"What we've got here is failure to communicate",
	"Who's on First?",
	"Why a Duck?",
	"You're gonna need a bigger boat"],
	// Proverbs
	["All that glitters is not gold",
	"All work and no play makes Jack a dull boy",
	"All's Well That Ends Well",
	"An apple a day keeps the doctor away",
	"Blood is thicker than water",
	"Curiosity killed the cat",
	"The devil is in the detail",
	"Don't count your chickens before they hatch",
	"Don't cross the bridge until you come to it",
	"Even a worm will turn",
	"It ain't over till the fat lady sings",
	"Many happy returns",
	"Necessity is the mother of invention",
	"A picture is worth a thousand words",
	"There's many a slip 'twixt the cup and the lip",
	"When life gives you lemons, make lemonade"],
	// idioms
	["Achilles' heel",
	"Adam's ale",
	"All singing, all dancing",
	"All the tea in China",
	"Apples and oranges",
	"As easy as pie",
	"As the crow flies",
	"Back-seat driver",
	"Barking up the wrong tree",
	"Glossary of English-language idioms derived from baseball",
	"Bed of roses",
	"Belling the cat",
	"Best friends forever",
	"Between Scylla and Charybdis",
	"Between the devil and the deep blue sea",
	"Black sheep",
	"Blood, toil, tears, and sweat",
	"Bootstrapping",
	"Born in the purple",
	"The Boy Who Cried Wolf",
	"Bread and butter",
	"Break a leg",
	"Buck passing",
	"Bum rushing",
	"Bum steer",
	"Call a spade a spade",
	"The captain goes down with the ship",
	"Carrot and stick",
	"Cart before the horse",
	"Cat and mouse",
	"Cheating death",
	"Chink in one's armor",
	"Chip on shoulder",
	"Circle the wagons",
	"Cloak and dagger",
	"Cold shoulder",
	"Crime of the century",
	"Crocodile tears",
	"Crying wolf",
	"Curiosity killed the cat",
	"Curiosity killed the cat, but satisfaction brought it back",
	"Cutting off the nose to spite the face",
	"Cutty-sark",
	"Damning with faint praise",
	"Dark horse",
	"Dead ringer",
	"Death and taxes",
	"The devil is in the detail",
	"Devil's advocate",
	"Die with your boots on",
	"The Dog in the Manger",
	"Don't count your chickens before they hatch",
	"Don't judge a book by its cover",
	"Don't throw the baby out with the bathwater",
	"Down Under",
	"Dressing down",
	"Duck test",
	"Eating crow",
	"Eating your own dog food",
	"Elbow grease",
	"Elephant in the room",
	"Exception that proves the rule",
	"Eye for an eye",
	"Fatted calf",
	"A feather in your cap",
	"Flogging a dead horse",
	"Foot the bill",
	"Forbidden fruit",
	"Forty winks",
	"Freudian slip",
	"Fruit of the poisonous tree",
	"Get a life",
	"Getting the wind knocked out of you",
	"The good doctor",
	"Good turn",
	"Grain of salt",
	"Greatest thing since sliced bread",
	"Hail fellow well met",
	"Hair's breadth",
	"Ham it up",
	"Head start",
	"Henny Penny",
	"Hobson's choice",
	"Hoist with his own petard",
	"Hold your horses",
	"Holy cow",
	"Humble pie",
	"Intimate part",
	"Is the glass half empty or half full?",
	"Jack of all trades, master of none",
	"Jumping from the frying pan into the fire",
	"Keeping up with the Joneses",
	"Kick the bucket",
	"Kick the cat",
	"The lady doth protest too much, methinks",
	"Law of the instrument",
	"Learning the hard way",
	"Lion's share",
	"Live and Let Live",
	"The living daylights",
	"Logrolling",
	"Mad as a March hare",
	"Make a mountain out of a molehill",
	"Man bites dog",
	"Man Friday",
	"The Man",
	"Man's best friend",
	"Marketplace of ideas",
	"Medicine chest",
	"Mexican standoff",
	"Mind your Ps and Qs",
	"Misnomer",
	"Monkey's uncle",
	"Morgue file",
	"Mufti",
	"Mum's the word",
	"No comment",
	"Oldest profession",
	"Out of the blue",
	"Pain in the ass",
	"Pea soup fog",
	"Pearls before swine",
	"Pig in a poke",
	"Pork barrel",
	"The pot calling the kettle black",
	"Powder keg",
	"The powers that be",
	"Primrose path",
	"The quick and the dead",
	"Rags to riches",
	"Raining cats and dogs",
	"The real McCoy",
	"Red herring",
	"Red-light district",
	"Reinventing the wheel",
	"Rest in peace",
	"Salad days",
	"Sands of time",
	"The Satyr and the Traveller",
	"School of Hard Knocks",
	"Sea change",
	"Second childhood",
	"Second fiddle",
	"Shut up",
	"Silver bullet",
	"Silver lining",
	"Silver spoon",
	"Simple matter of software",
	"Sin City",
	"Sisyphean task",
	"Sitting on the fence",
	"Skeleton in the closet",
	"Skin of my teeth",
	"Sliced bread",
	"Smoke and mirrors",
	"Snap-of-a-finger",
	"Speak of the devil",
	"Spitting distance",
	"List of sports idioms",
	"Square peg in a round hole",
	"Stalking horse",
	"Stiff upper lip",
	"Stir crazy",
	"A stone's throw away",
	"Stop press",
	"Straw that broke the camel's back",
	"Sweetness and light",
	"Takes two to tango",
	"Taking the piss",
	"Tall tale",
	"Teaching grandmother to suck eggs",
	"Tell it to the Marines",
	"Tempest in a teapot",
	"There but for the grace of God go I",
	"There's many a slip 'twixt the cup and the lip",
	"Those who live in glass houses should not throw stones",
	"Tilting at windmills",
	"Tip of the tongue",
	"Toe the line",
	"Tongue-in-cheek",
	"Too cheap to meter",
	"The Town Mouse and the Country Mouse",
	"Trial of the century",
	"Trip the light fantastic",
	"Turn in one's grave",
	"Twiddly bits",
	"University of Life",
	"Up to eleven",
	"War chest",
	"Waving a dead chicken",
	"What's done is done",
	"White elephant",
	"The whole nine yards",
	"A wigwam for a goose's bridle",
	"Wolf in sheep's clothing",
	"Work spouse",
	"Average Joe",
	"Baby mama",
	"Bang for the buck",
	"Catbird seat",
	"Chinaman's chance",
	"D'oh!",
	"The dog ate my homework",
	"Get the hell out of Dodge",
	"Going postal",
	"Heebie-jeebies",
	"Hot take",
	"I know it when I see it",
	"I say it's spinach",
	"Indian giver",
	"Ladies who lunch",
	"Loose lips sink ships",
	"My two cents",
	"My way or the highway",
	"Nancy Reagan defense",
	"Nosebleed section",
	"Peanut gallery",
	"Playing by ear",
	"Popularity contest",
	"Race card",
	"Rainbow Over Texas",
	"Sacred cow",
	"Say Uncle",
	"Tantamount to election",
	"The creek don't rise",
	"The squeaky wheel gets the grease",
	"Throw under the bus",
	"Tinkerbell effect",
	"You kids get off my lawn!"],
	// Ad Slogans
	["A diamond is forever",
	"A Diamond is Forever",
	"Advertising slogan",
	"Aflacts",
	"Age of the Train",
	"Beef. It's What's For Dinner",
	"The best things come to those who wait",
	"Better Living Through Chemistry",
	"Bo Knows",
	"Buy NZ Made",
	"Clunk Click Every Trip",
	"Corinthian leather",
	"The customer is not a moron",
	"Dan Smith Will Teach You Guitar",
	"Does exactly what it says on the tin",
	"Don't Hold Others Back",
	"Fahrvergnügen",
	"For Your Consideration",
	"Gambling Hangover",
	"Get Your Sexy Back",
	"Go Greyhound and Leave the Driving to Us",
	"Go to work on an egg",
	"Good things come to those who wait",
	"Got Milk?",
	"I Am Canadian",
	"I am Dunedin",
	"I learned it by watching you!",
	"I Love New York",
	"I Love the World",
	"I Want My Maypo",
	"I'm going to Disney World!",
	"The Incredible, Edible Egg",
	"Jingle",
	"Just Do It",
	"Just Say No",
	"The Kid in You",
	"Kiss a Little Longer",
	"Last Best West",
	"Legalize LA",
	"Life. Be in it.",
	"Make.believe",
	"Metronatural",
	"Miller Time",
	"The Most Interesting Man in the World",
	"Not happy, Jan!",
	"One weekend a month, two weeks a year",
	"The Other Iraq",
	"Pay to surf",
	"Pilipinas Kay Ganda",
	"Pork. The Other White Meat",
	"Proud as a Peacock",
	"Recycle It, Don't Trash It!",
	"Shrimp on the barbie",
	"Slip-Slop-Slap",
	"So where the bloody hell are you?",
	"The Spirit of Radio",
	"Tagline",
	"Think different",
	"Think Small",
	"This Is Your Brain on Drugs",
	"Us Tareyton smokers would rather fight than switch!",
	"Virginia is for Lovers",
	"We answer to a higher authority",
	"We Bring Good Things to Life",
	"Whassup?",
	"When Heaven Was at the Corner of Sycamore and Main",
	"Where's the beef?",
	"Who Makes Movies?",
	"Winners Don't Use Drugs",
	"Winston tastes good like a cigarette should",
	"World famous in New Zealand",
	"Wow Philippines",
	"Write once, run anywhere",
	"Yeh Dil Maange More!",
	"You Got the Right One, Baby",
	"You Press the Button, We Do the Rest",
	"You Will"]]